### ISSUE TITLE
Modernize Repo

### ISSUE THREAD

**Issue by Aaronontheweb** [AkkaNetContrib/Akka.TestKit.VsTest#19]
- [ ] NUKE Build system
- [ ] `Directory.Build.Props`
- [ ] GitHub Actions
- [ ] Dependabot
- [ ] https://github.com/akkadotnet/Akka.TestKit.VsTest/issues/18
- [ ] https://github.com/akkadotnet/Akka.TestKit.VsTest/issues/15

**Comment by eaba** [comment]
https://github.com/akkadotnet/Akka.TestKit.VsTest/pull/20

* NUKE Build system

![image](https://user-images.githubusercontent.com/8049896/206808674-a89cb7b1-e336-4417-80ee-3ffc2127c644.png)
 
* `Directory.Build.Props`

![image](https://user-images.githubusercontent.com/8049896/206809008-5d8faa68-2ccb-45b7-b4a1-37ad7165fc4b.png)

* GitHub Actions

![image](https://user-images.githubusercontent.com/8049896/206809231-c9d7f08a-a96c-4784-b3d9-b8a766112609.png)

* MSTest .NET Core and Standard 2.0

![image](https://user-images.githubusercontent.com/8049896/206809760-0c0c7edc-58ce-4bf5-8cd0-d9766c9e2d6b.png)

* Dependabot

**Comment by Aaronontheweb** [comment]
Send a PR!

**Comment by eaba** [comment]
https://github.com/akkadotnet/Akka.TestKit.VsTest/pull/20

**Comment by Aaronontheweb** [comment]
Merged that PR so CI can run - have not done a review yet, otherwise

**Comment by Aaronontheweb** [comment]
We definitely need to update all of the metadata in https://github.com/akkadotnet/Akka.TestKit.VsTest/blob/dev/src/Directory.Build.props
